version: 2
jobs:
  integration_tests:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout

#      - run:
#          name: install dependencies
#          command: make venv
#
#      - run:
#          name: 'Integration Tests'
#          no_output_timeout: 20m
#          command: |
#            export LOGGING_CONF_FILE=$(pwd)/sample_logging.conf
#            make integration_test

workflows:
  version: 2
  build:
    jobs:
      - integration_tests
